<?php

$strFiltro = filter_input(INPUT_GET, 'strFiltro', FILTER_SANITIZE_STRING);

if (strlen($strFiltro) == 0) {
    echo json_encode('Entrada Vazia');
    die();
}


$paises = [
    ['codigo' => 'US', 'nome' => 'United States'],
    ['codigo' => 'GB', 'nome' => 'United Kingdom'],
    ['codigo' => 'CA', 'nome' => 'Canada'],
    ['codigo' => 'AF', 'nome' => 'Afghanistan'],
    ['codigo' => 'AX', 'nome' => 'Aland Islands'],
    ['codigo' => 'AL', 'nome' => 'Albania'],
    ['codigo' => 'DZ', 'nome' => 'Algeria'],
    ['codigo' => 'AS', 'nome' => 'American Samoa'],
    ['codigo' => 'AD', 'nome' => 'Andorra'],
    ['codigo' => 'AO', 'nome' => 'Angola'],
    ['codigo' => 'AI', 'nome' => 'Anguilla'],
    ['codigo' => 'AQ', 'nome' => 'Antarctica'],
    ['codigo' => 'AG', 'nome' => 'Antigua And Barbuda'],
    ['codigo' => 'AR', 'nome' => 'Argentina'],
    ['codigo' => 'AM', 'nome' => 'Armenia'],
    ['codigo' => 'AN', 'nome' => 'Netherlands Antilles'],
    ['codigo' => 'AW', 'nome' => 'Aruba'],
    ['codigo' => 'AU', 'nome' => 'Australia'],
    ['codigo' => 'AT', 'nome' => 'Austria'],
    ['codigo' => 'AZ', 'nome' => 'Azerbaijan'],
    ['codigo' => 'BS', 'nome' => 'Bahamas'],
    ['codigo' => 'BH', 'nome' => 'Bahrain'],
    ['codigo' => 'BD', 'nome' => 'Bangladesh'],
    ['codigo' => 'BB', 'nome' => 'Barbados'],
    ['codigo' => 'BY', 'nome' => 'Belarus'],
    ['codigo' => 'BE', 'nome' => 'Belgium'],
    ['codigo' => 'BZ', 'nome' => 'Belize'],
    ['codigo' => 'BJ', 'nome' => 'Benin'],
    ['codigo' => 'BM', 'nome' => 'Bermuda'],
    ['codigo' => 'BT', 'nome' => 'Bhutan'],
    ['codigo' => 'BO', 'nome' => 'Bolivia'],
    ['codigo' => 'BA', 'nome' => 'Bosnia And Herzegovina'],
    ['codigo' => 'BW', 'nome' => 'Botswana'],
    ['codigo' => 'BV', 'nome' => 'Bouvet Island'],
    ['codigo' => 'BR', 'nome' => 'Brazil'],
    ['codigo' => 'IO', 'nome' => 'British Indian Ocean Territory'],
    ['codigo' => 'BN', 'nome' => 'Brunei Darussalam'],
    ['codigo' => 'BG', 'nome' => 'Bulgaria'],
    ['codigo' => 'BF', 'nome' => 'Burkina Faso'],
    ['codigo' => 'BI', 'nome' => 'Burundi'],
    ['codigo' => 'KH', 'nome' => 'Cambodia'],
    ['codigo' => 'CM', 'nome' => 'Cameroon'],
    ['codigo' => 'CA', 'nome' => 'Canada'],
    ['codigo' => 'CV', 'nome' => 'Cape Verde'],
    ['codigo' => 'KY', 'nome' => 'Cayman Islands'],
    ['codigo' => 'CF', 'nome' => 'Central African Republic'],
    ['codigo' => 'TD', 'nome' => 'Chad'],
    ['codigo' => 'CL', 'nome' => 'Chile'],
    ['codigo' => 'CN', 'nome' => 'China'],
    ['codigo' => 'CX', 'nome' => 'Christmas Island'],
    ['codigo' => 'CC', 'nome' => 'Cocos (Keeling) Islands'],
    ['codigo' => 'CO', 'nome' => 'Colombia'],
    ['codigo' => 'KM', 'nome' => 'Comoros'],
    ['codigo' => 'CG', 'nome' => 'Congo'],
    ['codigo' => 'CD', 'nome' => 'Congo, Democratic Republic'],
    ['codigo' => 'CK', 'nome' => 'Cook Islands'],
    ['codigo' => 'CR', 'nome' => 'Costa Rica'],
    ['codigo' => 'CI', 'nome' => 'Cote D\'Ivoire'],
    ['codigo' => 'HR', 'nome' => 'Croatia'],
    ['codigo' => 'CU', 'nome' => 'Cuba'],
    ['codigo' => 'CY', 'nome' => 'Cyprus'],
    ['codigo' => 'CZ', 'nome' => 'Czech Republic'],
    ['codigo' => 'DK', 'nome' => 'Denmark'],
    ['codigo' => 'DJ', 'nome' => 'Djibouti'],
    ['codigo' => 'DM', 'nome' => 'Dominica'],
    ['codigo' => 'DO', 'nome' => 'Dominican Republic'],
    ['codigo' => 'EC', 'nome' => 'Ecuador'],
    ['codigo' => 'EG', 'nome' => 'Egypt'],
    ['codigo' => 'SV', 'nome' => 'El Salvador'],
    ['codigo' => 'GQ', 'nome' => 'Equatorial Guinea'],
    ['codigo' => 'ER', 'nome' => 'Eritrea'],
    ['codigo' => 'EE', 'nome' => 'Estonia'],
    ['codigo' => 'ET', 'nome' => 'Ethiopia'],
    ['codigo' => 'FK', 'nome' => 'Falkland Islands (Malvinas)'],
    ['codigo' => 'FO', 'nome' => 'Faroe Islands'],
    ['codigo' => 'FJ', 'nome' => 'Fiji'],
    ['codigo' => 'FI', 'nome' => 'Finland'],
    ['codigo' => 'FR', 'nome' => 'France'],
    ['codigo' => 'GF', 'nome' => 'French Guiana'],
    ['codigo' => 'PF', 'nome' => 'French Polynesia'],
    ['codigo' => 'TF', 'nome' => 'French Southern Territories'],
    ['codigo' => 'GA', 'nome' => 'Gabon'],
    ['codigo' => 'GM', 'nome' => 'Gambia'],
    ['codigo' => 'GE', 'nome' => 'Georgia'],
    ['codigo' => 'DE', 'nome' => 'Germany'],
    ['codigo' => 'GH', 'nome' => 'Ghana'],
    ['codigo' => 'GI', 'nome' => 'Gibraltar'],
    ['codigo' => 'GR', 'nome' => 'Greece'],
    ['codigo' => 'GL', 'nome' => 'Greenland'],
    ['codigo' => 'GD', 'nome' => 'Grenada'],
    ['codigo' => 'GP', 'nome' => 'Guadeloupe'],
    ['codigo' => 'GU', 'nome' => 'Guam'],
    ['codigo' => 'GT', 'nome' => 'Guatemala'],
    ['codigo' => 'GG', 'nome' => 'Guernsey'],
    ['codigo' => 'GN', 'nome' => 'Guinea'],
    ['codigo' => 'GW', 'nome' => 'Guinea-Bissau'],
    ['codigo' => 'GY', 'nome' => 'Guyana'],
    ['codigo' => 'HT', 'nome' => 'Haiti'],
    ['codigo' => 'HM', 'nome' => 'Heard Island & Mcdonald Islands'],
    ['codigo' => 'VA', 'nome' => 'Holy See (Vatican City State)'],
    ['codigo' => 'HN', 'nome' => 'Honduras'],
    ['codigo' => 'HK', 'nome' => 'Hong Kong'],
    ['codigo' => 'HU', 'nome' => 'Hungary'],
    ['codigo' => 'IS', 'nome' => 'Iceland'],
    ['codigo' => 'IN', 'nome' => 'India'],
    ['codigo' => 'ID', 'nome' => 'Indonesia'],
    ['codigo' => 'IR', 'nome' => 'Iran, Islamic Republic Of'],
    ['codigo' => 'IQ', 'nome' => 'Iraq'],
    ['codigo' => 'IE', 'nome' => 'Ireland'],
    ['codigo' => 'IM', 'nome' => 'Isle Of Man'],
    ['codigo' => 'IL', 'nome' => 'Israel'],
    ['codigo' => 'IT', 'nome' => 'Italy'],
    ['codigo' => 'JM', 'nome' => 'Jamaica'],
    ['codigo' => 'JP', 'nome' => 'Japan'],
    ['codigo' => 'JE', 'nome' => 'Jersey'],
    ['codigo' => 'JO', 'nome' => 'Jordan'],
    ['codigo' => 'KZ', 'nome' => 'Kazakhstan'],
    ['codigo' => 'KE', 'nome' => 'Kenya'],
    ['codigo' => 'KI', 'nome' => 'Kiribati'],
    ['codigo' => 'KR', 'nome' => 'Korea'],
    ['codigo' => 'KW', 'nome' => 'Kuwait'],
    ['codigo' => 'KG', 'nome' => 'Kyrgyzstan'],
    ['codigo' => 'LA', 'nome' => 'Lao People\'s Democratic Republic'],
    ['codigo' => 'LV', 'nome' => 'Latvia'],
    ['codigo' => 'LB', 'nome' => 'Lebanon'],
    ['codigo' => 'LS', 'nome' => 'Lesotho'],
    ['codigo' => 'LR', 'nome' => 'Liberia'],
    ['codigo' => 'LY', 'nome' => 'Libyan Arab Jamahiriya'],
    ['codigo' => 'LI', 'nome' => 'Liechtenstein'],
    ['codigo' => 'LT', 'nome' => 'Lithuania'],
    ['codigo' => 'LU', 'nome' => 'Luxembourg'],
    ['codigo' => 'MO', 'nome' => 'Macao'],
    ['codigo' => 'MK', 'nome' => 'Macedonia'],
    ['codigo' => 'MG', 'nome' => 'Madagascar'],
    ['codigo' => 'MW', 'nome' => 'Malawi'],
    ['codigo' => 'MY', 'nome' => 'Malaysia'],
    ['codigo' => 'MV', 'nome' => 'Maldives'],
    ['codigo' => 'ML', 'nome' => 'Mali'],
    ['codigo' => 'MT', 'nome' => 'Malta'],
    ['codigo' => 'MH', 'nome' => 'Marshall Islands'],
    ['codigo' => 'MQ', 'nome' => 'Martinique'],
    ['codigo' => 'MR', 'nome' => 'Mauritania'],
    ['codigo' => 'MU', 'nome' => 'Mauritius'],
    ['codigo' => 'YT', 'nome' => 'Mayotte'],
    ['codigo' => 'MX', 'nome' => 'Mexico'],
    ['codigo' => 'FM', 'nome' => 'Micronesia, Federated States Of'],
    ['codigo' => 'MD', 'nome' => 'Moldova'],
    ['codigo' => 'MC', 'nome' => 'Monaco'],
    ['codigo' => 'MN', 'nome' => 'Mongolia'],
    ['codigo' => 'ME', 'nome' => 'Montenegro'],
    ['codigo' => 'MS', 'nome' => 'Montserrat'],
    ['codigo' => 'MA', 'nome' => 'Morocco'],
    ['codigo' => 'MZ', 'nome' => 'Mozambique'],
    ['codigo' => 'MM', 'nome' => 'Myanmar'],
    ['codigo' => 'NA', 'nome' => 'Namibia'],
    ['codigo' => 'NR', 'nome' => 'Nauru'],
    ['codigo' => 'NP', 'nome' => 'Nepal'],
    ['codigo' => 'NL', 'nome' => 'Netherlands'],
    ['codigo' => 'AN', 'nome' => 'Netherlands Antilles'],
    ['codigo' => 'NC', 'nome' => 'New Caledonia'],
    ['codigo' => 'NZ', 'nome' => 'New Zealand'],
    ['codigo' => 'NI', 'nome' => 'Nicaragua'],
    ['codigo' => 'NE', 'nome' => 'Niger'],
    ['codigo' => 'NG', 'nome' => 'Nigeria'],
    ['codigo' => 'NU', 'nome' => 'Niue'],
    ['codigo' => 'NF', 'nome' => 'Norfolk Island'],
    ['codigo' => 'MP', 'nome' => 'Northern Mariana Islands'],
    ['codigo' => 'NO', 'nome' => 'Norway'],
    ['codigo' => 'OM', 'nome' => 'Oman'],
    ['codigo' => 'PK', 'nome' => 'Pakistan'],
    ['codigo' => 'PW', 'nome' => 'Palau'],
    ['codigo' => 'PS', 'nome' => 'Palestinian Territory, Occupied'],
    ['codigo' => 'PA', 'nome' => 'Panama'],
    ['codigo' => 'PG', 'nome' => 'Papua New Guinea'],
    ['codigo' => 'PY', 'nome' => 'Paraguay'],
    ['codigo' => 'PE', 'nome' => 'Peru'],
    ['codigo' => 'PH', 'nome' => 'Philippines'],
    ['codigo' => 'PN', 'nome' => 'Pitcairn'],
    ['codigo' => 'PL', 'nome' => 'Poland'],
    ['codigo' => 'PT', 'nome' => 'Portugal'],
    ['codigo' => 'PR', 'nome' => 'Puerto Rico'],
    ['codigo' => 'QA', 'nome' => 'Qatar'],
    ['codigo' => 'RE', 'nome' => 'Reunion'],
    ['codigo' => 'RO', 'nome' => 'Romania'],
    ['codigo' => 'RU', 'nome' => 'Russian Federation'],
    ['codigo' => 'RW', 'nome' => 'Rwanda'],
    ['codigo' => 'BL', 'nome' => 'Saint Barthelemy'],
    ['codigo' => 'SH', 'nome' => 'Saint Helena'],
    ['codigo' => 'KN', 'nome' => 'Saint Kitts And Nevis'],
    ['codigo' => 'LC', 'nome' => 'Saint Lucia'],
    ['codigo' => 'MF', 'nome' => 'Saint Martin'],
    ['codigo' => 'PM', 'nome' => 'Saint Pierre And Miquelon'],
    ['codigo' => 'VC', 'nome' => 'Saint Vincent And Grenadines'],
    ['codigo' => 'WS', 'nome' => 'Samoa'],
    ['codigo' => 'SM', 'nome' => 'San Marino'],
    ['codigo' => 'ST', 'nome' => 'Sao Tome And Principe'],
    ['codigo' => 'SA', 'nome' => 'Saudi Arabia'],
    ['codigo' => 'SN', 'nome' => 'Senegal'],
    ['codigo' => 'RS', 'nome' => 'Serbia'],
    ['codigo' => 'SC', 'nome' => 'Seychelles'],
    ['codigo' => 'SL', 'nome' => 'Sierra Leone'],
    ['codigo' => 'SG', 'nome' => 'Singapore'],
    ['codigo' => 'SK', 'nome' => 'Slovakia'],
    ['codigo' => 'SI', 'nome' => 'Slovenia'],
    ['codigo' => 'SB', 'nome' => 'Solomon Islands'],
    ['codigo' => 'SO', 'nome' => 'Somalia'],
    ['codigo' => 'ZA', 'nome' => 'South Africa'],
    ['codigo' => 'GS', 'nome' => 'South Georgia And Sandwich Isl.'],
    ['codigo' => 'ES', 'nome' => 'Spain'],
    ['codigo' => 'LK', 'nome' => 'Sri Lanka'],
    ['codigo' => 'SD', 'nome' => 'Sudan'],
    ['codigo' => 'SR', 'nome' => 'Surinome'],
    ['codigo' => 'SJ', 'nome' => 'Svalbard And Jan Mayen'],
    ['codigo' => 'SZ', 'nome' => 'Swaziland'],
    ['codigo' => 'SE', 'nome' => 'Sweden'],
    ['codigo' => 'CH', 'nome' => 'Switzerland'],
    ['codigo' => 'SY', 'nome' => 'Syrian Arab Republic'],
    ['codigo' => 'TW', 'nome' => 'Taiwan'],
    ['codigo' => 'TJ', 'nome' => 'Tajikistan'],
    ['codigo' => 'TZ', 'nome' => 'Tanzania'],
    ['codigo' => 'TH', 'nome' => 'Thailand'],
    ['codigo' => 'TL', 'nome' => 'Timor-Leste'],
    ['codigo' => 'TG', 'nome' => 'Togo'],
    ['codigo' => 'TK', 'nome' => 'Tokelau'],
    ['codigo' => 'TO', 'nome' => 'Tonga'],
    ['codigo' => 'TT', 'nome' => 'Trinidad And Tobago'],
    ['codigo' => 'TN', 'nome' => 'Tunisia'],
    ['codigo' => 'TR', 'nome' => 'Turkey'],
    ['codigo' => 'TM', 'nome' => 'Turkmenistan'],
    ['codigo' => 'TC', 'nome' => 'Turks And Caicos Islands'],
    ['codigo' => 'TV', 'nome' => 'Tuvalu'],
    ['codigo' => 'UG', 'nome' => 'Uganda'],
    ['codigo' => 'UA', 'nome' => 'Ukraine'],
    ['codigo' => 'AE', 'nome' => 'United Arab Emirates'],
    ['codigo' => 'GB', 'nome' => 'United Kingdom'],
    ['codigo' => 'US', 'nome' => 'United States'],
    ['codigo' => 'UM', 'nome' => 'United States Outlying Islands'],
    ['codigo' => 'UY', 'nome' => 'Uruguay'],
    ['codigo' => 'UZ', 'nome' => 'Uzbekistan'],
    ['codigo' => 'VU', 'nome' => 'Vanuatu'],
    ['codigo' => 'VE', 'nome' => 'Venezuela'],
    ['codigo' => 'VN', 'nome' => 'Viet Nam'],
    ['codigo' => 'VG', 'nome' => 'Virgin Islands, British'],
    ['codigo' => 'VI', 'nome' => 'Virgin Islands, U.S.'],
    ['codigo' => 'WF', 'nome' => 'Wallis And Futuna'],
    ['codigo' => 'EH', 'nome' => 'Western Sahara'],
    ['codigo' => 'YE', 'nome' => 'Yemen'],
    ['codigo' => 'ZM', 'nome' => 'Zambia'],
    ['codigo' => 'ZW', 'nome' => 'Zimbabwe']];


$arrRetorno = array_filter($paises, function ($pais) use ($strFiltro) {

    $nomePais = strtolower($pais['nome']);
    $strFiltro = strtolower($strFiltro);

    if (strpos($nomePais,$strFiltro)!==false) {
        return true;
    } else {
        return false;
    }
});


echo json_encode(array_values($arrRetorno));